name: Update RSS Feed

on:
  schedule:
    - cron: '0 5 * * *'  # Runs daily at 8:00 AM Greek time (UTC+3)
  workflow_dispatch:  # Allows manual triggering of the workflow
  push:
    branches:
      - 'main'

jobs:
  update_rss:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Allow write access to the repository contents

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          gradle-version: 'current'

      # Step 5: Run the script
      - name: Run script
        run: gradle run

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'rss'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
